@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDU1NzU3NDF9.43JiT8ODgz-tL-5XX03NNyCvqRC-5CuBVPuxzqiGWmA

### product create
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "sheikh",
  "email": "sk@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### product create
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "sk@test.com",
  "password": "password"
}

### product index
GET http://localhost:3000/products
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDI3Mjk4MDJ9.m-uK0wbKXR8AAD7ibJFz8sXc7Gf7VzT3HY60TwNijhA

### product show
GET http://localhost:3000/products

### product create
POST http://localhost:3000/images
Content-Type: application/json

{
  "url": "https://www.mercedeshoffman.com/inventoryphotos/2603/wdcyc7hj6kx312828/ip/2.jpg?height=400",
  "product_id": 30
}

### product create
POST http://localhost:3000/images
Content-Type: application/json

{
  "url": "https://www.mercedeshoffman.com/inventoryphotos/2603/w1k3g4fbxnj333709/ip/1.jpg?height=400",
  "product_id": 1
}

### product update
delete http://localhost:3000/products/1
Content-Type: application/json



### product create
POST http://localhost:3000/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "product_id": 3,
  "quantity": 1
}

### product destroy
delete http://localhost:3000/images/2
Content-Type: application/json

###
get http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDM2NjAzNDN9.Qx0dp-pHJth5pY9spVvnfPacvqqmeSBw-p6D48akN58


### cartedproduct create
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDMyNDk3MDJ9.vPn0tYT5PkAMsh-AghSTSVWKiJRlj5xmptHcvFkfYqQ


### cartedproduct create
GET http://localhost:3000/cartedproducts
Content-Type: application/json
Authorization: Bearer {{jwt}}
