Product.create(name: "Mercedes-benz Class A", price: "42000", description: "brand new Merceded-benz Class A with navigation, led lights and panoramic roof")
Product.create(name: "Mercedes-benz Class C", price: "55000", description: "brand new Merceded-benz Class C with navigation, led lights and panoramic roof")
Product.create(name: "Mercedes-benz Class E", price: "810000", description: "brand new Merceded-benz Class E with navigation, led lights and panoramic roof")
Product.create(name: "Mercedes-benz Class S", price: "110000", description: "brand new Merceded-benz Class S with navigation, led lights and panoramic roof")
Product.create(name: "Mercedes-benz Class G", price: "240000", description: "brand new Merceded-benz Class G with navigation, led lights and panoramic roof")
